[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
mpl_corenft_pnft_staking = "your program ID"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/topstar/deployer.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
